name: CI/CD for WordPress

on:
  push:
    branches:
      - main  # Thay đổi trên nhánh main

jobs:
  build:
    runs-on: windows-latest  # Chạy trên Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Chọn phiên bản PHP phù hợp với WordPress

      - name: Install Composer dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Chọn phiên bản Node.js phù hợp

      - name: Install npm dependencies
        run: |
          npm install

      # - name: Build WordPress theme or plugin
      #   run: |
      #     npm run build

      - name: Copy only changed files to dist
        run: |
           mkdir -p dist
            # Lấy danh sách các tệp đã thay đổi
            changed_files=$(git diff --name-only HEAD^ HEAD)

            # Duyệt qua từng tệp và in ra đường dẫn của thư mục chứa nó
            for file in $changed_files; do
              dir=$(dirname "$file")
              echo "Đường dẫn thư mục chứa tệp thay đổi: $dir"
              
              # Sao chép tệp đã thay đổi vào thư mục dist
              rsync -R "$file" dist/
            done

      # - name: Deploy to FTP server
      #   uses: SamKirkland/FTP-Deploy-Action@4.0.0
      #   with:
      #     server: ${{ secrets.FTP_SERVER }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     port: 21
      #     protocol: ftp
      #     local-dir: ./dist/ 
      #     server-dir: ./public_html/  
